_target_: lsr.datasets.MultipleNegativesWithLabel
collection_path: /home/jingwen/raid-s1/projects/ms_embed_train/training/dataset/farfetch-triplets_with-category-splade-v1/docs.tsv
queries_path: /home/jingwen/raid-s1/projects/ms_embed_train/training/dataset/farfetch-triplets_with-category-splade-v1/queries.tsv
train_group_size: 8
triplet_ids_path: /home/jingwen/raid-s1/projects/ms_embed_train/training/dataset/farfetch-triplets_with-category-splade-v1/triplets.tsv
