_target_: lsr.datasets.MultipleNegatives
collection_path: /home/jingwen/raid-s1/projects/ms_embed_train/training/dataset/snapdeal-catalog-title-dedup-bge-v1/docs.tsv
queries_path: /home/jingwen/raid-s1/projects/ms_embed_train/training/dataset/snapdeal-catalog-title-dedup-bge-v1/queries.tsv
train_group_size: 8
triplet_ids_path: /home/jingwen/raid-s1/projects/ms_embed_train/training/dataset/snapdeal-catalog-title-dedup-bge-v1/triplets.tsv
